name: Engine tests Windows
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

env:
  BUILD_TYPE: DEBUG
  LIBRARIES_VERSION: 1

jobs:
  Test_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download libraries
        run: |
          Invoke-WebRequest -OutFile "libraries.exe" -Uri "https://api.creative-rift.com/api/download?platform=windows&v=LIBRARIES_VERSION&p=installer"
          ./libraries.exe > out.txt
          xcopy.exe /E /I .\libraries\${{env.BUILD_TYPE}}\ .\libraries\
          
          
      - name: Config tests
        run: |
          cd module/tests
          mkdir build
          cd build
          cmake -B ${{github.workspace}}/module/tests/build -G"Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

      - name: Build tests
        run: cmake --build ${{github.workspace}}/module/tests/build --config ${{env.BUILD_TYPE}}

      - name: Run tests
        run: |
          cd ${{github.workspace}}/module/tests/Debug
          ./SWEngine-testsd.exe