name: ShipWreck Engine Linux
on:
  workflow_dispatch:

env:
  BUILD_TYPE: DEBUG

jobs:
  Test_linux:
    runs-on: ubuntu-latest
    container: jfalcou/compilers:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Environement
        run: |
          ./check_for_update.sh -i
          mkdir build
          cd build
          cmake -B ${{github.workspace}}/build -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j 9